### PR TITLE
Action ordering in examples

### PR DESCRIPTION
**Pull request by manuel-delverme**
README.md + tests have the action order wrong.
It took me a while to understand it, trying to avoid overhead for other people.

### CODE REVIEW

**Comment by manuel-delverme** [comment]
I noticed the automatic refactoring ended up as a commit, lmk if i should rever that

**Comment by zafarali** [comment]
Hi Manuel Thanks for the changes as well as the linting! Everything looks good except b900218 which is causing the build to fail. Can you undo it and I will happily merge then :)

**Comment by manuel-delverme** [comment]
Oh wait those are extra changes that should not have been included in the pr

**Comment by zafarali** [comment]
Will you move the commit from here to another branch?

**Pull request closed without merging**
